### Auth
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
  "phone": "1234567890",
  "password": "1234567"
}


### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{ "name": "Nodirbek",
  "surname": "Hasanov",
  "email": "hasanovnodir0703@gmail.com",
  "password": "12345"
}


### Email verification
GET localhost:8080/api/v1/auth/verification/email/dasdasdasd
