### Create region
POST localhost:8080/api/v1/region/admin
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE0MjQ0NzEsInBob25lIjoiKzk5ODkxNTI1NDQ3NSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjkxNTEwODcxLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.AudabOkuBh7f9BFd7q5IQrWXGHlXbH3BN4MXJ0Ys0uZxlwv8OEB05HmkCR_NewfE6BliJeN0KWhQ6eHAC4j9dQ

{
  "orderNumber": 10,
  "nameEng": "Surxondaryo eng",
  "nameRu": "Surxondaryo ru",
  "nameUz": "Surxondaryo uz"
}


### update region
PUT localhost:8080/api/v1/region/admin/update?id=4
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE0MjQ0NzEsInBob25lIjoiKzk5ODkxNTI1NDQ3NSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjkxNTEwODcxLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.AudabOkuBh7f9BFd7q5IQrWXGHlXbH3BN4MXJ0Ys0uZxlwv8OEB05HmkCR_NewfE6BliJeN0KWhQ6eHAC4j9dQ


{
  "orderNumber": 100,
  "nameEng": "Namangan eng",
  "nameRu": "Namangan ru",
  "nameUz": "Namangan uz"
}

### delete region by id
DELETE localhost:8080/api/v1/region/admin/delete?id=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE0MjQ0NzEsInBob25lIjoiKzk5ODkxNTI1NDQ3NSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjkxNTEwODcxLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.AudabOkuBh7f9BFd7q5IQrWXGHlXbH3BN4MXJ0Ys0uZxlwv8OEB05HmkCR_NewfE6BliJeN0KWhQ6eHAC4j9dQ


### get region by pagination
GET localhost:8080/api/v1/region/admin/pagination?from=1&to=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE0MjQ0NzEsInBob25lIjoiKzk5ODkxNTI1NDQ3NSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjkxNTEwODcxLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.AudabOkuBh7f9BFd7q5IQrWXGHlXbH3BN4MXJ0Ys0uZxlwv8OEB05HmkCR_NewfE6BliJeN0KWhQ6eHAC4j9dQ

### get region by lang
GET localhost:8080/api/v1/region/language?lang=uz